# Generated by Django 3.1.4 on 2020-12-31 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybox', '0004_auto_20201231_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_on',
            field=models.DateField(default=datetime.date(2020, 12, 31)),
        ),
    ]
